### PR TITLE
chore(tx-builder): fix some inconsistencies in the docs

### LINKED ISSUE #298: Tx builder: document TransactionBuilder::send_coins()

### PR DESCRIPTION
**Pull request by Alex6323**
Closes #298 

Duplicate of #292

There are still some inconsistencies fixed by this PR.

### CODE REVIEW

File: crates/iota-transaction-builder/src/builder/mod.rs [hunk 1]
```diff
@@ -441,6 +441,39 @@ impl<C, L> TransactionBuilder<C, L> {
...
+    ///     )?;
+    ///     let gas_coin = ObjectId::from_str(
+    ///         "0x0b0270ee9d27da0db09651e5f7338dfa32c7ee6441ccefa1f6e305735bcfc7ab",
+    ///     )?;
+    ///
+    ///     let mut builder = TransactionBuilder::new(from_address).with_client(client);
+    ///     builder
+    ///         .send_coins([coin], to_address, 50000000000u64)
+    ///         .gas(gas_coin)
+    ///         .gas_budget(1000000000);
```
Comment (Thoralf-M) [inline crates/iota-transaction-builder/src/builder/mod.rs]: Would also remove the `gas_coin`, `.gas()` and `.gas_budget()` here as they are not needed

**Review by DaughterOfMars — COMMENTED** [review]
PR title is inaccurate

**Comment by thibault-martinez** [comment]
> PR title is inaccurate

Was there a failed merged? Or why is this PR not adding docs?

File: crates/iota-transaction-builder/src/builder/mod.rs (hunk 1 above)
Comment (Alex6323) [reply crates/iota-transaction-builder/src/builder/mod.rs]: well, already done in #292

**Comment by Alex6323** [comment]
> > PR title is inaccurate
> 
> Was there a failed merged? Or why is this PR not adding docs?

Duplicate issue!

**Review by thibault-martinez — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
