### PR TITLE
fix(kotlin): fail CI if example panics

### LINKED ISSUE #313: CI: failed kotlin example should make the CI fail
Right now it still passes also if an example failed: https://github.com/iotaledger/iota-rust-sdk/actions/runs/18499191019/job/52711141083?pr=246
```
iota_sdk.SdkFfiException$Generic: Timeout waiting for transaction finalization, digest: 6RRwMfnbYoZA88RZvd53yKacJDa82AdtZk6CDGKq4mYG
	at iota_sdk.FfiConverterTypeSdkFfiError.read(iota_sdk_ffi.kt:52301)
	at iota_sdk.FfiConverterTypeSdkFfiError.read(iota_sdk_ffi.kt:52297)
	at iota_sdk.FfiConverter.liftFromRustBuffer(iota_sdk_ffi.kt:202)
	at iota_sdk.FfiConverterRustBuffer.lift(iota_sdk_ffi.kt:219)
	at iota_sdk.SdkFfiException$ErrorHandler.lift(iota_sdk_ffi.kt:52290)
	at iota_sdk.SdkFfiException$ErrorHandler.lift(iota_sdk_ffi.kt:52289)
	at iota_sdk.Iota_sdk_ffiKt.uniffiCheckCallStatus(iota_sdk_ffi.kt:286)
	at iota_sdk.Iota_sdk_ffiKt.access$uniffiCheckCallStatus(iota_sdk_ffi.kt:1)
	at iota_sdk.Iota_sdk_ffiKt.uniffiRustCallAsync(iota_sdk_ffi.kt:57238)
	at iota_sdk.Iota_sdk_ffiKt$uniffiRustCallAsync$1.invokeSuspend(iota_sdk_ffi.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at GasStationKt.main(GasStation.kt:13)
	at GasStationKt.main(GasStation.kt)
```

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes https://github.com/iotaledger/iota-rust-sdk/issues/313

The Kotlin examples catch panics to display a stacktrace, preventing the error code from reaching the shell and then failing the CI. We then add an explicit error code after the stacktrace.

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

File: bindings/kotlin/examples/CoinBalances.kt [hunk 1]
```diff
@@ -13,6 +13,7 @@ fun main() = runBlocking {
                         "0xb14f13f5343641e5b52d144fd6f106a7058efe2f1ad44598df5cda73acf0101f",
                 )
 
+        error("panic")
```
Comment (Thoralf-M) [inline bindings/kotlin/examples/CoinBalances.kt]: Didn't see this commit yet when I approved

**Review by Thoralf-M — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
