### PR TITLE
fix(transaction-builder, examples): Fix gas budget calculation

### LINKED ISSUE #253: Tx builder: call dry_run_tx_kind() or dry_run() depending on what user set
Right now in ` pub async fn finish(mut self) -> Result<Transaction, Error> {` we always call dry_run() if no `gas_budget` was set to determine the gas budget.
If a gas coin was set, we should call `dry_run_tx_kind()` instead with the gas coins provided in `TransactionMetadata` (also the other fields if set)

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description

Fixes the gas budget calculation by calling `dry_run_tx_kind` instead of `dry_run_tx` and remove arbitrary gas budgets from examples.

Closes #253

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-graphql-client/examples/generic_move_function.rs [hunk 1]
```diff
@@ -25,7 +25,8 @@ async fn main() -> Result<()> {
         .move_call(Address::TWO, "vec_map", "from_keys_values")
         .generics::<(Address, u64)>()
         .arguments((vec![address1, address2], vec![10000000u64, 20000000u64]))
-        .gas("0xa1d009e8dafe20b1cba05e08aea488aafae1f89d892c3eaef6c0994e155e441a".parse()?);
+        .gas("0xa1d009e8dafe20b1cba05e08aea488aafae1f89d892c3eaef6c0994e155e441a".parse()?)
+        .gas_budget(1000000000);
```
Comment (Thoralf-M) [inline crates/iota-graphql-client/examples/generic_move_function.rs]: Why don't remove both things instead?

Comment (DaughterOfMars) [reply crates/iota-graphql-client/examples/generic_move_function.rs]: We'd also have to skip checks. I dunno 🤷‍♀️

File: bindings/go/examples/prepare_send_iota_multi/main.go [hunk 2]
```diff
@@ -36,15 +36,13 @@ func main() {
 	}
 
 	// Split the gas coin into multiple coins
```
Comment (Thoralf-M) [inline bindings/go/examples/prepare_send_iota_multi/main.go]:
```suggestion
	// Split a coin into multiple coins
```

**Review by Thoralf-M — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]
