### PR TITLE
fix: Remove unimplemented publish type

### LINKED ISSUE #273: Tx builder: impl load package from path
https://github.com/iotaledger/iota-rust-sdk/blob/5d5b17c0a8da0ccbbe9b48bca10de842176dade3/crates/iota-transaction-builder/src/publish_type.rs#L12

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description

Removes the unimplemented option to read a package from the file system, as I do not believe this is possible without significant effort. I also moved the `MovePackageData` type to a more appropriate location in the types crate, and implemented some more functionality for it.

Closes #273

### CODE REVIEW

File: crates/iota-transaction-builder/src/lib.rs [hunk 1]
```diff
@@ -331,11 +329,7 @@ mod tests {
 
         // we need this ticket to authorize the upgrade
         tx.move_call(Address::FRAMEWORK, "package", "authorize_upgrade")
-            .arguments((
-                upgrade_cap.unwrap(),
-                0u8,
-                updated_package.digest.as_ref().unwrap(),
-            ))
+            .arguments((upgrade_cap.unwrap(), 0u8, updated_package.digest))
```
Comment (Thoralf-M) [inline crates/iota-transaction-builder/src/lib.rs]: Let's also add this https://github.com/iotaledger/iota/blob/cb413841cbe11ece2fa1bc6d6b9d08832e028b77/crates/iota-types/src/move_package.rs#L120 and use it here instead of 0u8?

Comment (DaughterOfMars) [reply crates/iota-transaction-builder/src/lib.rs]: sure!

File: crates/iota-transaction-builder/src/lib.rs [hunk 2]
```diff
@@ -333,8 +331,8 @@ mod tests {
         tx.move_call(Address::FRAMEWORK, "package", "authorize_upgrade")
             .arguments((
                 upgrade_cap.unwrap(),
-                0u8,
-                updated_package.digest.as_ref().unwrap(),
+                UpgradePolicy::Additive as u8,
```
Comment (thibault-martinez) [inline crates/iota-transaction-builder/src/lib.rs]: This was Compatible and is now Additive?

Comment (DaughterOfMars) [reply crates/iota-transaction-builder/src/lib.rs]: whoops

File: crates/iota-sdk-ffi/src/transaction_builder/mod.rs [hunk 3]
```diff
@@ -260,17 +260,13 @@ impl TransactionBuilder {
     ///    the package
     pub fn publish(
         self: Arc<Self>,
-        modules: Vec<Vec<u8>>,
+        package_data: &MovePackageData,
         dependencies: Vec<Arc<ObjectId>>,
```
Comment (thibault-martinez) [inline crates/iota-sdk-ffi/src/transaction_builder/mod.rs]: Wouldn't `package_data` already contain dependencies?

Comment (DaughterOfMars) [reply crates/iota-sdk-ffi/src/transaction_builder/mod.rs]: oops, yeah

File: crates/iota-sdk-ffi/src/types/move_package.rs [hunk 4]
```diff
@@ -0,0 +1,63 @@
+// Copyright (c) 2025 IOTA Stiftung
+// SPDX-License-Identifier: Apache-2.0
+
+use std::sync::Arc;
+
+use crate::{error::Result, types::object::ObjectId};
+
+#[derive(derive_more::From, uniffi::Object)]
+pub struct UpgradePolicy(pub iota_types::UpgradePolicy);
```
Comment (thibault-martinez) [inline crates/iota-sdk-ffi/src/types/move_package.rs:10]: For this and MovePackageData, bring the two doc comments from the rust crate?

Comment (DaughterOfMars) [reply crates/iota-sdk-ffi/src/types/move_package.rs:10]: done

**Review by Thoralf-M — APPROVED** [review]

File: crates/iota-sdk-ffi/src/types/move_package.rs [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+use std::sync::Arc;
+
+use crate::{error::Result, types::object::ObjectId};
+
+/// Representation of upgrade policy constants in `iota::package`.
+#[derive(derive_more::From, uniffi::Object)]
+pub struct UpgradePolicy(pub iota_types::UpgradePolicy);
+
+#[uniffi::export]
+impl UpgradePolicy {
```
Comment (thibault-martinez) [inline crates/iota-sdk-ffi/src/types/move_package.rs:13]: `is_valid_policy` not wanted/needed?

**Review by thibault-martinez — APPROVED** [review]

File: crates/iota-sdk-ffi/src/types/move_package.rs (hunk 5 above)
Comment (DaughterOfMars) [reply crates/iota-sdk-ffi/src/types/move_package.rs:13]: I don't know

Comment (thibault-martinez) [reply crates/iota-sdk-ffi/src/types/move_package.rs:13]: Ah I didn't see it was an associated function anyway
